export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";
export const CHAT_LIST_RESET = "CHAT_LIST_RESET";

export const SELECTED_CHAT_REQUEST = "SELECTED_CHAT_REQUEST";
export const SELECTED_CHAT_SUCCESS = "SELECTED_CHAT_SUCCESS";
export const SELECTED_CHAT_FAIL = "SELECTED_CHAT_FAIL";
export const SELECTED_CHAT_RESET = "SELECTED_CHAT_RESET";

