export const CHAT_LIST_REQUEST = "CHAT_LIST_REQUEST";
export const CHAT_LIST_SUCCESS = "CHAT_LIST_SUCCESS";
export const CHAT_LIST_FAIL = "CHAT_LIST_FAIL";
export const CHAT_LIST_RESET = "CHAT_LIST_RESET";

export const SELECTED_CHAT_REQUEST = "SELECTED_CHAT_REQUEST";
export const SELECTED_CHAT_SUCCESS = "SELECTED_CHAT_SUCCESS";
export const SELECTED_CHAT_FAIL = "SELECTED_CHAT_FAIL";
export const SELECTED_CHAT_RESET = "SELECTED_CHAT_RESET";

export const SEND_MESSAGE_REQUEST = "SEND_MESSAGE_REQUEST";
export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAIL = "SEND_MESSAGE_FAIL";


export const GET_MESSAGES_REQUEST = "GET_MESSAGES_REQUEST";
export const GET_MESSAGES_SUCCESS = "GET_MESSAGES_SUCCESS";
export const GET_MESSAGES_FAIL = "GET_MESSAGES_FAIL";
export const GET_MESSAGES_RESET = "GET_MESSAGES_RESET";

export const GET_UNREAD_MESSAGES_REQUEST = "GET_UNREAD_MESSAGES_REQUEST";
export const GET_UNREAD_MESSAGES_SUCCESS = "GET_UNREAD_MESSAGES_SUCCESS";
export const GET_UNREAD_MESSAGES_FAIL = "GET_UNREAD_MESSAGES_FAIL";
export const GET_UNREAD_MESSAGES_RESET = "GET_UNREAD_MESSAGES_RESET";