export const NOTIFICATION_SUCCESS = "NOTIFICATION_SUCCESS";
export const NOTIFICATION_REQUEST = "NOTIFICATION_REQUEST";
export const NOTIFICATION_FAIL = "NOTIFICATION_FAIL";
export const NOTIFICATION_RESET = "NOTIFICATION_RESET";



export const UNREAD_NOTIFICATION_SUCCESS = "UNREAD_NOTIFICATION_SUCCESS";
export const UNREAD_NOTIFICATION_REQUEST = "UNREAD_NOTIFICATION_REQUEST";
export const UNREAD_NOTIFICATION_FAIL = "UNREAD_NOTIFICATION_FAIL";
export const UNREAD_NOTIFICATION_RESET = "UNREAD_NOTIFICATION_RESET";