export const POST_REQUEST = "POST_REQUEST";
export const POST_SUCCESS = "POST_SUCCESS";
export const POST_FAIL = "POST_FAIL";


export const POST_LIST_REQUEST = "POST_LIST_REQUEST";
export const POST_LIST_SUCCESS = "POST_LIST_SUCCESS";
export const POST_LIST_FAIL = "POST_LIST_FAIL";
export const POST_LIST_RESET = "POST_LIST_RESET";

export const POST_ALL_LIST_REQUEST = "POST_ALL_LIST_REQUEST";
export const POST_ALL_LIST_SUCCESS = "POST_ALL_LIST_SUCCESS";
export const POST_ALL_LIST_FAIL = "POST_ALL_LIST_FAIL";
export const POST_ALL_LIST_RESET = "POST_ALL_LIST_RESET";


export const POST_LIST_ONEUSER_REQUEST = "POST_LIST_ONEUSER_REQUEST";
export const POST_LIST_ONEUSER_SUCCESS = "POST_LIST_ONEUSER_SUCCESS";
export const POST_LIST_ONEUSER_FAIL = "POST_LIST_ONEUSER_FAIL";
export const POST_LIST_ONEUSER_RESET = "POST_LIST_ONEUSER_RESET";


export const POST_DELETE_REQUEST = "POST_DELETE_REQUEST";
export const POST_DELETE_SUCCESS = "POST_DELETE_SUCCESS";
export const POST_DELETE_FAIL = "POST_DELETE_FAIL";
export const POST_DELETE_RESET = "POST_DELETE_RESET";