

export const REPLY_DELETE_REQUEST = "REPLY_DELETE_REQUEST";
export const REPLY_DELETE_SUCCESS = "REPLY_DELETE_SUCCESS";
export const REPLY_DELETE_FAIL = "REPLY_DELETE_FAIL";
export const REPLY_DELETE_RESET = "REPLY_DELETE_RESET";



